Repository frenck/python-demetriek, pull requests merged in 2023-03, with the labels that each got.

#378 Improve pydantic model default and alias handling
  examples/example.py
  poetry.lock
  pyproject.toml
  src/demetriek/models.py
Labels: enhancement

#398 Refactor on many levels
  .deepsource.toml
  .devcontainer/devcontainer.json
  .editorconfig
  .flake8
  .github/LICENSE.md
  .github/dependabot.yml
  .github/renovate.json
  .github/workflows/codeql.yaml
  .github/workflows/labels.yaml
  .github/workflows/linting.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release.yaml
  .github/workflows/requirements.txt
  .github/workflows/stale.yaml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  .nvmrc
  .pre-commit-config.yaml
  .yamllint
  README.md
  examples/ruff.toml
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  src/demetriek/cloud.py
  src/demetriek/device.py
  src/demetriek/models.py
  tests/__init__.py
  tests/ruff.toml
  tests/test_apps.py
  tests/test_audio.py
  tests/test_bluetooth.py
  tests/test_cloud.py
  tests/test_device.py
  tests/test_display.py
  tests/test_lametric.py
  tests/test_wifi.py
Labels: breaking-change, refactor

#401 Add configuration for SonarCloud
  sonar-project.properties
Labels: ci

#404 Workflow adjustments/fixes for PRs from forks
  .github/workflows/pr-labels.yaml
  .github/workflows/tests.yaml
Labels: ci

#405 Pass PR number when checking for PR labels
  .github/workflows/pr-labels.yaml
Labels: ci

#288 Add ability to enable/disable screensaver
  src/demetriek/device.py
  src/demetriek/models.py
  tests/fixtures/display_set.json
  tests/test_device.py
  tests/test_display.py
Labels: new-feature
