Repository frenck/python-demetriek, pull requests merged in 2024-12, with the labels that each got.

#741 ci: Fix ruff linting.
  .github/workflows/linting.yaml
  .pre-commit-config.yaml
Labels: refactor

#742 Apply ruff pre-commit to all files.
  src/demetriek/cloud.py
  src/demetriek/device.py
  src/demetriek/models.py
Labels: refactor

#744 Add include hidden files option to artifact upload.
  .github/workflows/tests.yaml
Labels: maintenance

#745 Remove async_timeouts and replace it with asyncio.timeouts.
  src/demetriek/cloud.py
  src/demetriek/device.py
Labels: refactor

#743 Fix typo on the code of conduct file.
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#746 Remove deprecation warnings when running ruff
  examples/ruff.toml
  pyproject.toml
  tests/ruff.toml
Labels: maintenance

#749 Remove unused black dependencies
  poetry.lock
  pyproject.toml
Labels: maintenance

#750 Update linters/formatters/precommit to match other projects
  .github/workflows/linting.yaml
  .pre-commit-config.yaml
  pyproject.toml
  src/demetriek/__init__.py
  src/demetriek/cloud.py
  src/demetriek/device.py
  src/demetriek/models.py
  tests/__init__.py
  tests/test_apps.py
  tests/test_audio.py
  tests/test_bluetooth.py
  tests/test_cloud.py
  tests/test_device.py
  tests/test_display.py
  tests/test_lametric.py
  tests/test_wifi.py
Labels: maintenance

#740 Replace pydantic with mashumaro
  poetry.lock
  pyproject.toml
  src/demetriek/cloud.py
  src/demetriek/device.py
  src/demetriek/models.py
  tests/fixtures/notification.json
  tests/test_device.py
Labels: refactor

#752 Add Python 3.13
  .github/workflows/tests.yaml
  pyproject.toml
  sonar-project.properties
Labels: maintenance

#562 Extend support for LaMetric SKY on state
  src/demetriek/device.py
  src/demetriek/models.py
  tests/fixtures/display.json
  tests/fixtures/display_set.json
  tests/test_display.py
Labels: stale, new-feature

#720 Added support for LaMetric SKY devices and SoundURL model for notification
  src/demetriek/__init__.py
  src/demetriek/const.py
  src/demetriek/device.py
  src/demetriek/models.py
  tests/test_device.py
  tests/test_display.py
Labels: new-feature
