Repository frenck/python-demetriek, pull requests merged in 2025-01, with the labels that each got.

#780 Fix serialization of notifications with no sound
  src/demetriek/models.py
Labels: bugfix

#781 Handle devices reporting no audio support (Sky)
  src/demetriek/models.py
Labels: bugfix

#782 :fireworks: Updates maintenance/license year to 2025
  .github/LICENSE.md
  README.md
Labels: maintenance

#783 Migrate ruff configuration
  tests/ruff.toml
Labels: maintenance

#789 Migrate pre-commit config
  .pre-commit-config.yaml
Labels: maintenance

#788 Add brightness range to display model
  src/demetriek/models.py
  tests/test_display.py
Labels: new-feature
